### ISSUE TITLE
Disable Native Option

### ISSUE THREAD

**Issue by timbofield** [chemerisuk/better-dateinput-polyfill#33]
Chrome is now using its native date picker. Is there a way to force the polyfill version ? ( I realise that isn't much of a polyfill, but I / my client only wants the native for mobile devices )

**Comment by chemerisuk** [comment]
@timbofield anyway I think it's a good idea to have such option. What about `data-native` attribute that might have values `"desktop"`, `"mobile"` that allows to suppress native control on demand? If it doesn't exist, then current "true polyfill" checks are applied to determine which strategy to use. Otherwise you can control if you want native control or not on element-level. Or you want to set such setting globally?

**Comment by timbofield** [comment]
@chemerisuk yes I was just thinking that as well, data-native would be good. I see this line has been added at some point, wasn't in older versions.

https://github.com/chemerisuk/better-dateinput-polyfill/blob/master/src/main.js#L13

**Comment by timbofield** [comment]
Setting globally would be a 'nice to have' feature

**Comment by chemerisuk** [comment]
@timbofield yeah, the second argument of `DOM.extend` is a functor, that controls if live extension is applied or not and it accepts the matched element. Therefore the implementation is pretty simple. Just need to find some free time on it :)

I think it's better to keep this option on element-level only. It's kind of making a polyfill to be not a true polyfill, so some developers might be confused. Therefore an implementor should understand clearly  what he or she is doing, that's why always specify `data-native` for every new `input[type=date]`element.

**Comment by chemerisuk** [comment]
Released in 1.5.2 ;)

**Comment by timbofield** [comment]
Fantastic, its working well :)

**Comment by BrodaNoel** [comment]
Please, add documentation about it.

**Comment by chemerisuk** [comment]
will do

**Comment by chemerisuk** [comment]
@BrodaNoel readme was updated
