### ISSUE TITLE
display:none instead of visible: hidden

### ISSUE THREAD

**Issue by BrodaNoel** [chemerisuk/better-dateinput-polyfill#44]
Hi @chemerisuk !
I'm looking in you code that when you need to hide something, you are using `visible: hidden` insted of `display: none`.
Why did you do that?

The `display: none` is better to hide tags that "contain" a width and a height...
For example, if you have 3 divs next each other, if you `visible: hidden` the last 2 divs, the "father" div that contain the 3 blocks will continue having the height as if the 3 blocks are visible...

**Comment by chemerisuk** [comment]
I use `visible: hidden` instead of `display: none` because of two reasons:
1) `visible: hidden` is more performant, because it triggers only repaint while `display: none` triggers reflow as well 
2) you can't use CSS3 animations with `display: none`

You `position:absolute` if you need to move element out of the flow. Also I suggest to read https://github.com/chemerisuk/better-dom/wiki/Declarative-animations
