### ISSUE TITLE
Ability to type in values

### ISSUE THREAD

**Issue by sgentile** [chemerisuk/better-dateinput-polyfill#50]
Since we can't easily change year - the native browser for chrome lets you type in a value  (ie. for a birthdate).

Is it possible with the polyfill to allow someone to type in the value ?   I tried on Safari desktop and it didn't allow this.

**Comment by chemerisuk** [comment]
@sgentile yeah, I was thinking about this feature in the past. Since handling of text selection is quite tricky (and buggy) from browser to browser, I'd rather implement https://github.com/chemerisuk/better-dateinput-polyfill/issues/8 instead of allowing a user manual input.

Please don't ask me about estimates - not sure when I'll be back to Open Source... Quite busy this year with other stuff ;)

**Comment by chemerisuk** [comment]
I like how Chrome solves the problem in their implementation:

<img width="144" alt="screenshot 2016-04-21 12 27 37" src="https://cloud.githubusercontent.com/assets/274044/14704305/a38f3dca-07bc-11e6-9237-facc148a53d6.png">

May be we could schedule this feature for 2.1.

**Comment by chemerisuk** [comment]
No go because of approach used in version 3 to customise presented value
