### ISSUE TITLE
Text color stays transparent for hidden inputs

### ISSUE THREAD

**Issue by loganfranken** [chemerisuk/better-dateinput-polyfill#58]
This is extremely specific, but:

If you have a `input[type="date"]` that is initially hidden and is only revealed *after* the polyfill has initialized, then the text color will remain transparent upon selecting a date.

Here's a demo of this:
https://jsfiddle.net/mahvfon2/2/

For the real world context: I have a page with tabs that the users can click to show/reveal different panes of content. The `input[type="date"]`s are within these panes, causing the situation demoed above.

I was able to fix this by listening for the "change" event on these inputs and then changing the color.

(Wonderful polyfill, by the way!)

**Comment by chemerisuk** [comment]
@loganfranken nice bug indeed. I'd recommend to use visibility:hidden in your case if possible that should solve the problem too.

**Comment by sylvainpolletvillard** [comment]
Have the same issue when using the polyfill within an Angular component

**Comment by talss89** [comment]
I had the same issue, using the polyfill in an Angular view. There's a CSS solution to this; set a z-index on `.btr-dateinput-value`. I think the actual input colour *should* remain transparent.

I'm using Bootstrap 3.x, and the following worked for me.

```CSS
.btr-dateinput-value {
  z-index: 3
}
```

I'm not sure if '3' should be the final z-index value in the packaged CSS (otherwise I'd make a pull request), but it's along the right lines.
